package com.kingboya.common.bgm.entity;

import javax.persistence.*;

@Table(name = "tabple_emp")
public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tabple_emp.emp_id
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tabple_emp.emp_name
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tabple_emp.emp_salary
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    private Double empSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tabple_emp.emp_age
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    private Integer empAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tabple_emp.emp_id
     *
     * @return the value of tabple_emp.emp_id
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tabple_emp.emp_id
     *
     * @param empId the value for tabple_emp.emp_id
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tabple_emp.emp_name
     *
     * @return the value of tabple_emp.emp_name
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tabple_emp.emp_name
     *
     * @param empName the value for tabple_emp.emp_name
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tabple_emp.emp_salary
     *
     * @return the value of tabple_emp.emp_salary
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    public Double getEmpSalary() {
        return empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tabple_emp.emp_salary
     *
     * @param empSalary the value for tabple_emp.emp_salary
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    public void setEmpSalary(Double empSalary) {
        this.empSalary = empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tabple_emp.emp_age
     *
     * @return the value of tabple_emp.emp_age
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    public Integer getEmpAge() {
        return empAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tabple_emp.emp_age
     *
     * @param empAge the value for tabple_emp.emp_age
     *
     * @mbg.generated Fri Aug 30 15:12:18 CST 2019
     */
    public void setEmpAge(Integer empAge) {
        this.empAge = empAge;
    }
}